name: 'Eclipse plug-in deployment to server'
description: 'Provides the facility to deploy versioned Maven-built Eclipse plug-ins to an ssh host.'
inputs:
  remote-host:
    description: 'Remote host'
    required: true
  remote-user:
    description: 'Remote SSH user'
    required: true
  remote-root:
    description: 'Remote root folder'
    required: true
  remote-baseurl:
    description: 'Remote url basis'
    required: true
  remote-relative-path:
    description: 'Remote path for deployment relative to root'
    required: true
  remote-ssh-key:
    description: 'User SSH private key'
    required: true
  ssh-fingerprint:
    descirption: 'Remote SSH public key fingerprint'
    required: false
  ssh-fingerprint-type:
    descirption: 'Remote SSH public key fingerprint type'
    required: false
  comment:
    description: 'Insert commit comment with URL on success'
    required: false
    default: true
  maven-target:
    description: 'Name of maven target folder'
    required: true
outputs:
  version:
    description: 'Version of the plug-in'
    value: ${{ steps.get-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: get-version
      run: ${{ github.action_path }}/get_version.sh \"${{ maven-target }}\"
      shell: bash

    - name: Add SSH known hosts
      run: echo "${{inputs.remote-host}} ${{ inputs.ssh-fingerprint-type }} ${{ inputs.ssh-fingerprint }}" >> ~/.ssh/known_hosts
      shell: bash

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        # Private key required to access the host
        ssh-private-key: ${{ inputs.remote-ssh-key }}

    - id: upload
      run: >
          ${{ github.action_path }}/upload.sh
          \"${{ inputs.maven-target }}\"
          \"${{ inputs.email }}\"
          \"${{ steps.get-version.outputs.version }}\"
          \"${{ inputs.remote-user }}@${{ inputs.remote-host }}\"
          \"${{ inputs.remote-root }}/${{ inputs.relative-path }}\"
      shell: bash

    - if: ${{ inputs.comment }} == true
      name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: Successfully deployed at: ${{ remote-baseurl }}/${{ remote-relative-path }}${{ steps.upload.outputs.dest }}
